# Server configuration
SERVER_HOST = '127.0.0.1'
SERVER_PORT = 5555

# Game settings
DEFAULT_TIME_LIMIT = 15  # minutes
MAX_PLAYERS_IN_LOBBY = 100
MAX_GAMES = 50

# GUI settings
BOARD_SIZE = 600
SQUARE_SIZE = BOARD_SIZE // 8
PADDING = 20
CHAT_WIDTH = 300
WINDOW_WIDTH = BOARD_SIZE + CHAT_WIDTH + PADDING * 3
WINDOW_HEIGHT = BOARD_SIZE + PADDING * 2
